name: Build INT64 Wheel

on:
  workflow_dispatch:
  push:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Build Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environments/all_cuda-131_arch-x86_64.yaml
          environment-name: cuopt_build
          cache-environment: true

      - name: Build Wheel
        shell: bash -el {0}
        env:
          EXTRA_CMAKE_ARGS: "-DCUOPT_INSTANTIATE_INT64=ON -DCUOPT_INSTANTIATE_INT32=OFF"
        run: |
          ./build.sh libmps_parser libcuopt cuopt \
            --skip-tests-build \
            --cmake-args "${EXTRA_CMAKE_ARGS}"

      - name: Upload Wheel as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuopt-int64-wheel
          path: python/cuopt/dist/*.whl
